import { useMemo, useState } from 'react';
import { collection, getDocs, query, where } from 'firebase/firestore';
import { db } from '../lib/firebase';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent } from '@/components/ui/card';
import { Download, Mail, Printer, Search } from 'lucide-react';

type Row = { id:string; fullName?:string; mobileNumber?:string; district?:string; placePost?:string; selectedSubject?:string; messageBody?:string; emailId?:string; toRecipients?:string; ccRecipients?:string; submissionStatus?:string; emailLaunchStatus?:string; createdAt?:any; submittedAt?:string; date?:string; time?:string };
type Scope = 'date'|'range'|'all';

const todayKey=()=>{const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const localKey=(r:Row)=>{const raw=r.createdAt?.toDate?.() || (r.submittedAt?new Date(r.submittedAt):null); if(raw && !Number.isNaN(raw.getTime())) return `${raw.getFullYear()}-${String(raw.getMonth()+1).padStart(2,'0')}-${String(raw.getDate()).padStart(2,'0')}`; const m=String(r.date||'').match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/); return m?`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:'';};
const timeText=(r:Row)=>r.time || (r.createdAt?.toDate?.()?r.createdAt.toDate().toLocaleTimeString('en-IN'):(r.submittedAt?new Date(r.submittedAt).toLocaleTimeString('en-IN'):'-'));
const csv=(v:any)=>`"${String(v??'').replace(/"/g,'""')}"`;

export default function JanamailAdminReport(){
 const [scope,setScope]=useState<Scope>('date'); const [date,setDate]=useState(todayKey()); const [from,setFrom]=useState(todayKey()); const [to,setTo]=useState(todayKey());
 const [allRows,setAllRows]=useState<Row[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [scanned,setScanned]=useState(false); const [search,setSearch]=useState('');
 const run=async()=>{setLoading(true);setError('');try{const snap=await getDocs(query(collection(db,'claims'),where('recordType','==','janamail_submission')));setAllRows(snap.docs.map(d=>({id:d.id,...d.data()} as Row)).sort((a,b)=>String(b.submittedAt||'').localeCompare(String(a.submittedAt||''))));setScanned(true);}catch(e:any){setError(e?.message||'Janamail report failed');}finally{setLoading(false);}};
 const scoped=useMemo(()=>allRows.filter(r=>{const k=localKey(r); if(scope==='all')return true; if(scope==='range')return !!k&&k>=from&&k<=to; return k===date;}),[allRows,scope,date,from,to]);
 const rows=useMemo(()=>{const q=search.trim().toLowerCase(); if(!q)return scoped; return scoped.filter(r=>[r.fullName,r.mobileNumber,r.emailId,r.district,r.placePost,r.selectedSubject,r.toRecipients,r.ccRecipients].some(v=>String(v||'').toLowerCase().includes(q)));},[scoped,search]);
 const downloadAll=()=>{const head=['#','Date','Time','Name','Sender Email','Mobile','District','Place/Post','TO','CC','Subject','Submission','Mail Launch','Record ID'];const lines=[head.map(csv).join(',')];rows.forEach((r,i)=>lines.push([i+1,localKey(r),timeText(r),r.fullName,r.emailId,r.mobileNumber,r.district,r.placePost,r.toRecipients||'Not stored in older record',r.ccRecipients||'Not stored in older record',r.selectedSubject,r.submissionStatus,r.emailLaunchStatus,r.id].map(csv).join(',')));const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`janamail-${scope==='all'?'all':scope==='range'?`${from}-to-${to}`:date}.csv`;a.click();URL.revokeObjectURL(a.href);};
 const printReport=()=>window.print();
 return <Card className="border-2 border-indigo-200 bg-white print:border-0"><CardContent className="p-4 space-y-3">
  <div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="font-black text-slate-950 flex items-center gap-2"><Mail className="w-5 h-5"/>Janamail — Admin Report</h3><p className="text-xs font-bold text-slate-600">Date, date-range or complete Janamail sending report.</p></div>
   <div className="flex flex-wrap items-end gap-2 print:hidden"><Button variant={scope==='date'?'default':'outline'} onClick={()=>setScope('date')}>Date</Button><Button variant={scope==='range'?'default':'outline'} onClick={()=>setScope('range')}>Date Range</Button><Button variant={scope==='all'?'default':'outline'} onClick={()=>setScope('all')}>ALL</Button>
    {scope==='date'&&<label className="text-xs font-black text-slate-700">Date<Input type="date" value={date} onChange={e=>setDate(e.target.value)} className="mt-1 bg-white text-slate-950 [color-scheme:light]"/></label>}
    {scope==='range'&&<><label className="text-xs font-black text-slate-700">From<Input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="mt-1 bg-white text-slate-950 [color-scheme:light]"/></label><label className="text-xs font-black text-slate-700">To<Input type="date" value={to} onChange={e=>setTo(e.target.value)} className="mt-1 bg-white text-slate-950 [color-scheme:light]"/></label></>}
    <Button onClick={run} disabled={loading} className="bg-indigo-700 text-white"><Search className="w-4 h-4 mr-2"/>{loading?'Loading…':'Load Report'}</Button></div></div>
  <div className="flex flex-wrap gap-2 items-end print:hidden"><div className="min-w-64 flex-1"><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, Gmail, mobile, district, recipient..."/></div><Button onClick={downloadAll} disabled={!scanned}><Download className="w-4 h-4 mr-2"/>Download {scope==='all'?'ALL':'Filtered'} CSV</Button><Button onClick={printReport} disabled={!scanned}><Printer className="w-4 h-4 mr-2"/>Print / PDF</Button></div>
  {scanned&&!error&&<div className="rounded-xl bg-indigo-50 border border-indigo-200 p-3"><span className="text-xs font-black text-indigo-900">TOTAL EMAILS IN REPORT</span><div className="text-3xl font-black text-indigo-950">{rows.length}</div></div>}
  {error&&<div className="rounded-lg border border-red-300 bg-red-50 p-3 text-sm font-bold text-red-900">{error}</div>}
  {scanned&&!loading&&!error&&rows.length===0&&<p className="text-sm font-bold text-slate-600">No Janamail records found for this selection.</p>}
  {rows.length>0&&<div className="max-h-[360px] overflow-auto border rounded-xl print:max-h-none print:overflow-visible"><table className="w-full min-w-[1500px] text-xs text-left text-slate-950"><thead className="bg-slate-200 sticky top-0 z-10 print:static"><tr>{['#','Date','Time','Name','Sender Gmail','Mobile','District','Place / Post','TO','CC','Subject','Submission','Mail Launch','Record ID'].map(x=><th key={x} className="p-2 font-black">{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id} className="border-t align-top"><td className="p-2">{i+1}</td><td className="p-2 whitespace-nowrap">{localKey(r)||'-'}</td><td className="p-2 whitespace-nowrap">{timeText(r)}</td><td className="p-2 font-black">{r.fullName||'-'}</td><td className="p-2 break-all">{r.emailId||'-'}</td><td className="p-2 font-bold">{r.mobileNumber||'-'}</td><td className="p-2">{r.district||'-'}</td><td className="p-2">{r.placePost||'-'}</td><td className="p-2 max-w-72 break-all">{r.toRecipients||'Not stored in older record'}</td><td className="p-2 max-w-72 break-all">{r.ccRecipients||'Not stored in older record'}</td><td className="p-2 max-w-72 whitespace-normal">{r.selectedSubject||'-'}</td><td className="p-2"><Badge className="bg-emerald-100 text-emerald-950">{r.submissionStatus||'-'}</Badge></td><td className="p-2">{r.emailLaunchStatus||'-'}</td><td className="p-2 font-mono break-all">{r.id}</td></tr>)}</tbody></table></div>}
 </CardContent></Card>;
}
